# Generated by Django 5.2.8 on 2025-11-08 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_employee'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='aboust',
            new_name='about',
        ),
    ]
